# 【Q023】async/await


::: tip Issue
欢迎在 Gtihub Issue 中回答此问题: [Issue 23](https://github.com/kangyana/daily-question/issues/23)
:::

::: tip Author
回答者: [kangyana](https://github.com/kangyana)
:::
## 1. async 函数
`async` 函数是使用 **async关键字** 声明的函数。`async` 函数是 `AsyncFunction` 构造函数的实例， 并且其中允许使用 **await关键字**。
**async和await关键字** 让我们可以用一种更简洁的方式写出基于`Promise` 的异步行为，而无需刻意地链式调用 `promise`。

在函数前面的 **async关键字** 做了一件事情：使用函数始终返回一个 promise。其他值将自动被包装在一个 resolved 的 promise 中。
```javascript
async function f() {
  return 1;
}

async function f2() {
  return Promise.resolve(1);
}

f().then(console.log); // 1
f2().then(console.log); // 1
```

## 2. await 关键字
`await` 让 JavaScript 引擎等待直到 promise 完成（settle）并返回结果。
```javascript
async function f() {
  var promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("done!"), 1000)
  });

  var result = await promise; // 等待，直到 promise resolve (*)
  console.log(result); // "done!"
}

f();
```
这个函数在执行的时候，“暂停”在了` (*)` 那一行，并在 promise settle 时，拿到 `result` 作为结果继续往下执行。
所以上面这段代码在一秒后显示 “done!”。

强调一下：await 实际上会暂停函数的执行，直到 promise 状态变为 settled，然后以 promise 的结果继续执行。
这个行为不会耗费任何 CPU 资源，因为 JavaScript 引擎可以同时处理其他任务：执行其他脚本，处理事件等。

相比于 promise.then，它只是获取 promise 的结果的一个更优雅的语法，并且也更易于读写。

## 3. Error 处理
如果一个 promise 正常 resolve，`await promise` 返回的就是其结果。
但是如果 promise 被 reject，它将 throw 这个 error，就像在这一行有一个 `throw` 语句那样。

可以在函数调用后面添加 .catch 来处理这个 error：
```javascript
async function f() {
  var response = await fetch('http://no-such-url/');
}

// f() 变成了一个 rejected 的 promise
f().catch(console.log); // TypeError: failed to fetch // (*)
```

## 4. 总结
函数前面的关键字 async 有两个作用：

- 让这个函数总是返回一个 promise。
- 允许在该函数内使用 await。

Promise 前的关键字 await 使 JavaScript 引擎等待该 promise settle，然后有两种情况：

- 如果有 error，就会抛出异常 —— 就像那里调用了 throw error 一样。
- 否则，就返回结果。


